import { ColorScheme, allColors, withAlpha } from "../../shared";

export const getGitLensColors = (scheme: ColorScheme) => {
	const colors = allColors[scheme];
	const { bg0, bg1, bg3, grey, fg1, red, orange, blue, green } = colors;

	return {
		"gitlens.closedAutolinkedIssueIconColor": orange,
		"gitlens.closedPullRequestIconColor": red,
		"gitDecoration.addedResourceForeground": green,
		"gitlens.decorations.branchAheadForegroundColor": orange,
		"gitlens.decorations.branchBehindForegroundColor": orange,
		"gitlens.decorations.branchDivergedForegroundColor": orange,
		"gitlens.decorations.branchMissingUpstreamForegroundColor": red,
		"gitlens.decorations.statusMergingOrRebasingConflictForegroundColor": red,
		"gitlens.decorations.statusMergingOrRebasingForegroundColor": orange,
		"gitlens.decorations.workspaceCurrentForegroundColor": orange,
		"gitlens.decorations.workspaceRepoMissingForegroundColor": bg3,
		"gitlens.decorations.workspaceRepoOpenForegroundColor": orange,
		"gitlens.decorations.worktreeHasUncommittedChangesForegroundColor": grey,
		"gitlens.decorations.worktreeMissingForegroundColor": red,
		"gitlens.graphChangesColumnAddedColor": orange,
		"gitlens.graphChangesColumnDeletedColor": red,
		"gitlens.graphLane1Color": blue,
		"gitlens.graphLane2Color": blue,
		"gitlens.graphLane3Color": orange,
		"gitlens.graphLane4Color": orange,
		"gitlens.graphLane5Color": grey,
		"gitlens.graphLane6Color": grey,
		"gitlens.graphLane7Color": grey,
		"gitlens.graphLane8Color": grey,
		"gitlens.graphLane9Color": orange,
		"gitlens.graphLane10Color": orange,
		"gitlens.graphMinimapMarkerHeadColor": orange,
		"gitlens.graphMinimapMarkerHighlightsColor": orange,
		"gitlens.graphMinimapMarkerLocalBranchesColor": blue,
		"gitlens.graphMinimapMarkerPullRequestsColor": orange,
		"gitlens.graphMinimapMarkerRemoteBranchesColor": blue,
		"gitlens.graphMinimapMarkerStashesColor": orange,
		"gitlens.graphMinimapMarkerTagsColor": bg3,
		"gitlens.graphMinimapMarkerUpstreamColor": grey,
		"gitlens.graphScrollMarkerHeadColor": orange,
		"gitlens.graphScrollMarkerHighlightsColor": grey,
		"gitlens.graphScrollMarkerLocalBranchesColor": blue,
		"gitlens.graphScrollMarkerPullRequestsColor": orange,
		"gitlens.graphScrollMarkerRemoteBranchesColor": blue,
		"gitlens.graphScrollMarkerStashesColor": orange,
		"gitlens.graphScrollMarkerTagsColor": bg3,
		"gitlens.graphScrollMarkerUpstreamColor": grey,
		"gitlens.gutterBackgroundColor": bg1,
		"gitlens.gutterForegroundColor": fg1,
		"gitlens.gutterUncommittedForegroundColor": blue,
		"gitlens.launchpadIndicatorAttentionColor": orange,
		"gitlens.launchpadIndicatorAttentionHoverColor": orange,
		"gitlens.launchpadIndicatorBlockedColor": red,
		"gitlens.launchpadIndicatorBlockedHoverColor": red,
		"gitlens.launchpadIndicatorMergeableColor": orange,
		"gitlens.launchpadIndicatorMergeableHoverColor": orange,
		"gitlens.lineHighlightBackgroundColor": bg1,
		"gitlens.lineHighlightOverviewRulerColor": blue,
		"gitlens.mergedPullRequestIconColor": orange,
		"gitlens.openAutolinkedIssueIconColor": orange,
		"gitlens.openPullRequestIconColor": orange,
		"gitlens.trailingLineBackgroundColor": withAlpha(bg0, 160),
		"gitlens.trailingLineForegroundColor": withAlpha(grey, 160),
		"gitlens.unpublishedChangesIconColor": orange,
		"gitlens.unpublishedCommitIconColor": orange,
		"gitlens.unpulledChangesIconColor": orange,
	};
};