import { ColorScheme, allColors, withAlpha } from "../shared";

export const getBaseColors = (scheme: ColorScheme) => {
	const colors = allColors[scheme];
	const {
		bg0,
		mantle,
		bg1,
		bg2,
		bg3,
		grey,
		fg1,
		fg2,
		orange,
		blue,
		green,
		red,
		yellow,
		mauve,
		teal,
		transparent,
		white,
	} = colors;

	const statusBarBorder = bg1;

	return {
		// BASE COLORS
		focusBorder: bg1,
		foreground: fg1,
		"widget.shadow": withAlpha(bg0, 48),
		"widget.border": bg1,
		"selection.background": withAlpha(blue, 128),
		errorForeground: red,
		"icon.foreground": fg1,
		// BUTTON
		"button.background": withAlpha(blue, 128),
		"button.foreground": fg1,
		"button.hoverBackground": withAlpha(blue, 96),
		// DROPDOWN
		"dropdown.background": bg0,
		"dropdown.border": bg1,
		"dropdown.foreground": fg1,
		// INPUT
		"input.background": bg0,
		"input.border": bg1,
		"input.foreground": fg1,
		"input.placeholderForeground": withAlpha(fg1, 96),
		"inputValidation.errorBorder": red,
		"inputValidation.errorBackground": red,
		"inputValidation.infoBorder": blue,
		"inputValidation.infoBackground": withAlpha(blue, 128),
		"inputValidation.warningBorder": orange,
		"inputValidation.warningBackground": orange,
		"inputOption.activeBorder": withAlpha(fg1, 96),
		// SCROLL BAR
		"scrollbar.shadow": bg0,
		"scrollbarSlider.activeBackground": blue,
		"scrollbarSlider.hoverBackground": bg3,
		"scrollbarSlider.background": withAlpha(bg2, 153),
		// BADGE
		"badge.background": orange,
		"badge.foreground": white,
		// PROGRESS BAR
		"progressBar.background": blue,
		// LISTS AND TREES
		"list.activeSelectionBackground": withAlpha(bg1, 128),
		"list.activeSelectionForeground": blue,
		"list.hoverBackground": withAlpha(bg1, 128),
		"list.hoverForeground": fg2,
		"list.focusBackground": bg1,
		"list.focusForeground": fg1,
		"list.inactiveSelectionForeground": blue,
		"list.inactiveSelectionBackground": withAlpha(bg1, 128),
		"list.dropBackground": bg1,
		"list.highlightForeground": blue,
		// SIDE BAR
		"sideBar.background": mantle,
		"sideBar.foreground": fg2,
		"sideBar.border": bg1,
		"sideBarTitle.foreground": fg1,
		"sideBarSectionHeader.background": transparent,
		"sideBarSectionHeader.foreground": fg1,
		// ACTIVITY BAR
		"activityBar.background": bg0,
		"activityBar.foreground": fg1,
		"activityBar.border": bg1,
		"activityBarTop.background": bg0,
		"activityBarTop.foreground": fg1,
		"activityBarBadge.background": blue,
		"activityBarBadge.foreground": white,
		// EDITOR GROUPS
		"editorGroup.border": bg1,
		"editorGroup.dropBackground": withAlpha(bg1, 96),
		"editorGroupHeader.noTabsBackground": bg0,
		"editorGroupHeader.tabsBackground": bg0,
		"editorGroupHeader.tabsBorder": bg1,
		// TABS
		"tab.border": transparent,
		"tab.activeBorder": blue,
		"tab.activeBackground": bg1,
		"tab.activeForeground": fg1,
		"tab.inactiveForeground": grey,
		"tab.inactiveBackground": bg0,
		"tab.unfocusedActiveForeground": grey,
		"tab.unfocusedActiveBorder": transparent,
		"tab.unfocusedInactiveForeground": grey,
		// EDITOR
		"editor.background": bg0,
		"editor.foreground": fg1,
		"editorLineNumber.foreground": bg3,
		"editorCursor.foreground": fg1,
		"editor.selectionBackground": withAlpha(blue, 64),
		"editor.selectionHighlightBackground": withAlpha(bg2, 64),
		"editor.hoverHighlightBackground": withAlpha(blue, 80),
		"editorLink.activeForeground": fg1,
		"editor.findMatchBackground": withAlpha(blue, 112),
		"editor.findMatchHighlightBackground": withAlpha(orange, 48),
		"editor.findRangeHighlightBackground": withAlpha(blue, 112),
		"editor.lineHighlightBackground": withAlpha(bg1, 96),
		"editor.lineHighlightBorder": transparent,
		"editorWhitespace.foreground": withAlpha(grey, 32),
		"editorRuler.foreground": withAlpha(grey, 64),
		"editorCodeLens.foreground": withAlpha(grey, 144),
		"editorBracketMatch.border": transparent,
		"editorBracketMatch.background": withAlpha(grey, 128),
		"editorHoverWidget.background": bg0,
		"editorHoverWidget.border": bg1,
		"editorOverviewRuler.border": transparent,
		"editorOverviewRuler.findMatchForeground": fg2,
		"editorOverviewRuler.rangeHighlightForeground": fg2,
		"editorOverviewRuler.selectionHighlightForeground": bg3,
		"editorOverviewRuler.wordHighlightForeground": bg3,
		"editorOverviewRuler.wordHighlightStrongForeground": bg3,
		"editorOverviewRuler.modifiedForeground": blue,
		"editorOverviewRuler.addedForeground": green,
		"editorOverviewRuler.deletedForeground": red,
		"editorOverviewRuler.errorForeground": red,
		"editorOverviewRuler.warningForeground": orange,
		"editorOverviewRuler.infoForeground": blue,
		"editorGutter.background": transparent,
		"editorGutter.modifiedBackground": blue,
		"editorGutter.addedBackground": green,
		"editorGutter.deletedBackground": red,
		"editorError.foreground": red,
		"editorWarning.foreground": orange,
		"editorInfo.foreground": blue,
		"editorIndentGuide.activeBackground": bg3,
		// EDITOR - BRACKET PAIR COLORIZATION
		"editorBracketHighlight.foreground1": orange,
		"editorBracketHighlight.foreground2": blue,
		"editorBracketHighlight.foreground3": fg2,
		"editorBracketHighlight.foreground4": grey,
		"editorBracketHighlight.foreground5": orange,
		"editorBracketHighlight.foreground6": blue,
		"editorBracketHighlight.unexpectedBracket.foreground": red,
		// EDITOR - STICKY SCROLL
		"editorStickyScroll.shadow": withAlpha(bg2, 153),
		"editorStickyScrollHover.background": withAlpha(bg1, 96),
		// DIFF EDITOR
		"diffEditor.insertedTextBackground": withAlpha(green, 48),
		"diffEditor.removedTextBackground": withAlpha(red, 48),
		// WIDGET
		"editorWidget.background": bg0,
		"editorWidget.border": bg1,
		"editorSuggestWidget.background": bg0,
		"editorSuggestWidget.foreground": fg1,
		"editorSuggestWidget.highlightForeground": blue,
		"editorSuggestWidget.selectedBackground": withAlpha(bg1, 96),
		"editorSuggestWidget.border": bg1,
		// PEEK VIEW
		"peekView.border": bg1,
		"peekViewEditor.background": withAlpha(bg1, 112),
		"peekViewEditor.matchHighlightBackground": bg2,
		"peekViewEditorGutter.background": withAlpha(bg1, 112),
		"peekViewResult.background": withAlpha(bg1, 112),
		"peekViewResult.fileForeground": fg1,
		"peekViewResult.selectionBackground": withAlpha(blue, 32),
		"peekViewResult.selectionForeground": fg1,
		"peekViewResult.lineForeground": fg1,
		"peekViewResult.matchHighlightBackground": bg2,
		"peekViewTitle.background": withAlpha(bg1, 112),
		"peekViewTitleDescription.foreground": fg2,
		"peekViewTitleLabel.foreground": fg1,
		// MERGE CONFLICTS
		"merge.currentHeaderBackground": withAlpha(blue, 64),
		"merge.currentContentBackground": withAlpha(blue, 32),
		"merge.incomingHeaderBackground": withAlpha(orange, 64),
		"merge.incomingContentBackground": withAlpha(orange, 32),
		"merge.border": transparent,
		"editorOverviewRuler.currentContentForeground": blue,
		"editorOverviewRuler.incomingContentForeground": orange,
		"editorOverviewRuler.commonContentForeground": grey,
		// PANELS
		"panel.border": bg1,
		"panelTitle.activeForeground": fg1,
		// STATUS BAR
		"statusBar.background": mantle,
		"statusBar.border": statusBarBorder,
		"statusBar.foreground": fg1,
		"statusBar.debuggingBackground": orange,
		"statusBar.debuggingForeground": bg0,
		"statusBar.debuggingBorder": transparent,
		"statusBar.noFolderBackground": mantle,
		"statusBar.noFolderBorder": transparent,
		"statusBarItem.remoteBackground": mantle,
		"statusBarItem.remoteForeground": fg1,
		// INTEGRATED TERMINAL - Simplified palette
		"terminal.ansiBlack": bg1,
		"terminal.ansiBrightBlack": grey,
		"terminal.ansiRed": red,
		"terminal.ansiBrightRed": red,
		"terminal.ansiGreen": green,
		"terminal.ansiBrightGreen": green,
		"terminal.ansiYellow": yellow,
		"terminal.ansiBrightYellow": yellow,
		"terminal.ansiBlue": blue,
		"terminal.ansiBrightBlue": blue,
		"terminal.ansiMagenta": mauve,
		"terminal.ansiBrightMagenta": mauve,
		"terminal.ansiCyan": teal,
		"terminal.ansiBrightCyan": teal,
		"terminal.ansiWhite": grey,
		"terminal.ansiBrightWhite": fg1,
		"terminal.foreground": fg1,
		"terminal.background": bg0,
		// MENU BAR / TITLE BAR (match primary sidebar chrome)
		"menuBar.background": mantle,
		"menuBar.foreground": fg1,
		"titleBar.activeBackground": mantle,
		"titleBar.activeForeground": fg1,
		"titleBar.inactiveBackground": mantle,
		"titleBar.inactiveForeground": fg2,
		"titleBar.border": statusBarBorder,
		"commandCenter.border": statusBarBorder,
		"commandCenter.activeBorder": statusBarBorder,
		"commandCenter.inactiveBorder": statusBarBorder,
		"menu.background": mantle,
		"menu.foreground": fg1,
		"menu.border": statusBarBorder,
		"menu.separatorBackground": statusBarBorder,
		// GIT COLORS
		"gitDecoration.modifiedResourceForeground": blue,
		"gitDecoration.deletedResourceForeground": red,
		"gitDecoration.untrackedResourceForeground": green,
		"gitDecoration.addedResourceForeground": green,
		"gitDecoration.ignoredResourceForeground": bg3,
		"gitDecoration.conflictingResourceForeground": orange,
		"gitDecoration.stageModifiedResourceForeground": blue,
		"gitDecoration.stageDeletedResourceForeground": red,
		"gitDecoration.renamedResourceForeground": blue,
		"scmGraph.historyItemHoverLabelForeground": white,
		"scmGraph.historyItemHoverDefaultLabelForeground": white,
		// EXTENSIONS
		"extensionButton.prominentBackground": withAlpha(orange, 128),
		"extensionButton.prominentHoverBackground": withAlpha(orange, 48),
		// OTHERS
		"textLink.foreground": blue,
		"textLink.activeForeground": blue,
		"debugToolBar.background": bg0,
		"editorGhostText.background": withAlpha(bg3, 96),
	};
};